apiVersion: v1
kind: Secret
metadata:
    name: bws-secret
stringData:
    token: ENC[AES256_GCM,data:ug8Q8JnLxzWTRJXg7rQilpSNXSuYRlgj6Nk6j02fjVd5x5XckrAjhGYlFL2NisSuqvI9xKJFQ4cXrUPjPQBpPE/Doc54BcZe+Y7MqOcAdHN/zM23h4APsDYJhvkyXw==,iv:7WPOIJaR3rq7Qo26rD1fc0rOj7n5jcjBeWBp9aHppHw=,tag:2X610cHNCExR9JIQbw7Beg==,type:str]
    ORG_ID: ENC[AES256_GCM,data:Hl3j0EVaPSaTp+OfMpzDd/i2yknajiNhZhrCFjZLeKemvf5H,iv:gH7bhLQsRQHv4XoOcliFbq80uVNDMly2tZtTBMEx6w4=,tag:7c3MW9l5gCMhHIADN2blgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VWlhY0hKcmNpWkpZdjlN
            dGorSjVYYXZLTHdmRy9uNmxKZGJXN1dldUVnCjlyekUyTm1Jc2YrSjFERDBDeTVO
            VXhOM3N1bVk4VXMrN2EyeVExYmhvbVUKLS0tIDBGeTExZWpIYU10RHJFeHJyekt1
            K1ZqT2xsMm5oeklMclJQYjROQ2lOcGMK8lGvn7i+UHi0SBfxSFDa7WqU/N+YRrF4
            xjSOPEss1FMKLHXRfqXsaNV24EX45SsJxigSj5PBvdPGj8tmQiOq4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T17:21:36Z"
    mac: ENC[AES256_GCM,data:Gc/hCJX2batNX7fxAL7aCp3V8UPvxL5uywxg6B0VFBVWH1MgaAimHrYQoVG/NQPjy+AD5gZAhWDEq66tsNJrIXKyL3QABG09JW/XbE/fe+roAWTjABO8h4oImDH6849mV1HRvdK8i+CJ5cRZnof/5JjRQ0A1EjvzK90HPwIx3qo=,iv:ikpaBYu3sjM23qNOwPbKxz+BGDkOpmtcyotPpFiqeZQ=,tag:SVGVFIf5F038BED79/66Ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
