---
version: "3"

tasks:

  # Install bws cli.
  # If using fsh, uncomment "task: setup-path-fsh" and comment out "task: setup-path-zsh"
  # If using zsh, uncomment "task: setup-path-zsh" and comment out "task: setup-path-fsh"
  get-cli:
    desc: Install Bitwarden Secret Manager CLI
    cmds:
      - sudo apk add cargo
      - cargo install bws
      - task: setup-path-fsh
      # - task: setup-path-zsh
    preconditions:
      - { msg: "Bitwarden Secret Manager CLI already installed", sh: "! test -f /home/vscode/.cargo/bin/bws" }

  setup-path-fsh:
    desc: Setup Bitwarden Secret Manager CLI path for Fish shell
    cmds:
      - echo "SETUVAR fish_user_paths:/home/vscode/\x2ecargo/bin" >> ~/.config/fish/fish_variables
    preconditions:
      - { msg: "Bitwarden Secret Manager Fish CLI path already set", sh: "! fish -c 'echo $PATH | grep -q /home/vscode/.cargo/bin'" }

  setup-path-zsh:
    desc: Setup Bitwarden Secret Manager CLI path for Zsh shell
    cmds:
      - echo 'path+=("/home/vscode/.cargo/bin")' >> ~/.zshrc
      - source ~/.zshrc
    preconditions:
      - { msg: "Bitwarden Secret Manager ZSH CLI path already set", sh: "! grep -q '/home/vscode/.cargo/bin' ~/.zshrc" }

  # Push .kube/config to Bitwarden Secrets Manager
  push:
    desc: Push all kubeconfig to Secrets Manager
    dotenv: ['.env']
    cmds:
      - bws secret edit d9431909-6a07-4bac-b8aa-b14000b1f708 --access-token ${BW_ACCESS_TOKEN} --value "$(kubectl config view --flatten)"
      - bws secret edit b15d495b-ac16-4040-b62d-b14000b48248 --access-token ${BW_ACCESS_TOKEN} --value "$(kubectl config view --flatten | base64)"
      - task: push-main
    preconditions:
      - { msg: "Bitwarden Secret Manager CLI not found", sh: "test bws" }

  # Push kubeconfig to Bitwarden Secrets Manager
  push-main:
    desc: Push kubeconfig to Secrets Manager
    cmds:
      - bws secret edit ef390279-cfcd-4d70-a51c-b14000b400dc --access-token ${BW_ACCESS_TOKEN} --value "$(cat {{.ROOT_DIR}}/kubeconfig)"
    preconditions:
      - { msg: "Bitwarden Secret Manager CLI not found", sh: "test bws" }

  # Pull kubeconfig from Bitwarden Secrets Manager
  pull:
    desc: Pull Kubeconfig from Secrets Manager
    cmds:
      # - mkdir -p ~/.kube
      # - bws secret get d9431909-6a07-4bac-b8aa-b14000b1f708 --access-token ${BW_ACCESS_TOKEN} | jq -r '.value' > ~/.kube/config # Generic kubeconfig
      - bws secret get ef390279-cfcd-4d70-a51c-b14000b400dc --access-token ${BW_ACCESS_TOKEN} | jq -r '.value' > {{.ROOT_DIR}}/kubeconfig # Main kubeconfig
    preconditions:
      - { msg: "Bitwarden Secret Manager CLI not found", sh: "test bws" }
      - { msg: "JQ not found", sh: "test jq" }
