---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app infisical
spec:
  interval: 30m
  chart:
    spec:
      chart: secrets-operator
      version: 0.5.0
      # --set controllerManager.manager.image.tag=<PLACE-APP-VERSION-HERE>
      sourceRef:
        kind: HelmRepository
        name: infisical
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      infisical:
        type: deployment
        containers:
          app:
            image:
              repository: ghcr.io/infisical/secrets-operator
              tag: v0.5.0
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 2G
