---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./free-game-notifier/ks.yaml
  - ./misc-ingress/ks.yaml
  # - ./mosquitto/ks.yaml
  # - ./rss-forwarder/ks.yaml
  # - ./zigbee2mqtt/ks.yaml
