---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr-node
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: daemonset
    image:
      repository: ghcr.io/haveagitgat/tdarr_node_acc
      tag: 2.00.20.1
    env:
      TZ: "${TIMEZONE}"
      PUID: "1000"
      PGID: "1000"
      serverIP: ${NAS_IP}
      serverPort: 8266
      ffmpegPath: "/usr/local/bin/ffmpeg"
      nodeName:
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
    service:
      main:
        enabled: false
        ports:
          enabled: false
          http:
            port: 8265
    persistence:
      media:
        enabled: true
        existingClaim: downloads
        mountPath: /mnt/media
        subPath: media
      cache:
        enabled: true
        existingClaim: tdarr-cache
        mountPath: /temp
        subPath: temp
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
      capabilities:
        add:
          - CHOWN
      supplementalGroups:
        - 44
        - 226
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
        gpu.intel.com/i915: 1
      limits:
        gpu.intel.com/i915: 1
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
