---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tdarr-cache
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NAS_IP}
    path: ${SECRET_NFS_DATA}
  mountOptions:
    - nfsvers=4.2
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nocto
    - noacl
    - nconnect=8
    - rsize=131072
    - wsize=131072
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tdarr-cache
  namespace: downloads
spec:
  accessModes:
    - ReadWriteMany
  volumeName: tdarr-cache
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
