---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 30m
  # url: http://jameswynn.github.io/helm-charts
  url: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
  timeout: 3m
