---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./stakater.yaml
  # Added
  # - ./backube.yaml
  # - ./external-secrets.yaml
  - ./homepage.yaml
  - ./longhorn.yaml
  # - ./piraeus.yaml
  # - ./rook-ceph.yaml
