apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:0pGOwX42gNbSDBDtVZDyRJEAO3r/891YMCzM/pAm9f7nD1c0,iv:Q0xBnysJQa0oBIe4JLSG+38vfUgnKFctNIMNJyA7ciM=,tag:c5nwj/b+S5Y2GvcJsWgIBw==,type:str]
    credentials.json: ENC[AES256_GCM,data:5gUnzE/MMS+J9rr+3n2mld6LR+ybGx59MPgFT8KsymLtUskti9M0S4QxP7WhEP0P6BTDVd6rraGKA4oY/jpNC6qqcfXJwaMitkzMdz2HgtX7xxWLqCIedQQcHwxoYqT+A7iPDQFjUyjhhBogIDCmFAItTESC6zw8RrDEtqBzvaLTMcIWFJ0RUeFEDwDRKBoiNdkcuNzWDy1gOYrqgVI7CPIQZi0uFSixvZrOj+byJA==,iv:1KmL/enI/8VYvOZAeWgITRs3KFs08ICdmu9Pl4w41fc=,tag:r3TyHEXn7/UUIOhhJeLwMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NVZzcVh3RXhSZnlrdFl4
            SjR2TFplQTVYYmFEN0NYMUVuME1OUS9IM1FVCjdvVnBrRW0yZzMvdHNyWE5nb2Fm
            OFV5NU9PRDR3cVNyYTRGV1JvSFY5RW8KLS0tIFVadjJvR0NQb0R2RVR6Wi9NUVdO
            ZFVsRktydEhISk1VUFhPVFplT0wvc3cKhMjdMd+ZpAT/c5NmEyCiQewVoWqiC+W9
            U2cHThWKpzDqbV288+xT3Qq7tZTKTB3Df0MhsOdjH69F7dqZYoq2Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T15:48:44Z"
    mac: ENC[AES256_GCM,data:SAEY9vxAUVxmdAtqdxNE45gL81Oj5eac2AGyO1Eft7q6tX6m6WR2Xx8m/8Xr8w1+b9r4K008kW3U6FrW3a6L3svg4Ho8wXskQoCsrYH+NT5tcbwrJm9yqpokqBs7vAqpb1ukUhCkHoT1uaFHib0tZU1es+obusvfPZ6gxXlIoKg=,iv:Qfj0clh9frJ12VeQ9icABYj4mgtorfsa8smnUbzjy6U=,tag:HZBDhPdqeOTndIRdw4yyCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
