---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  - ./downloads-pvc.yaml
  # Flux-Kustomizations
  # - ./bazarr/ks.yaml
  # - ./prowlarr/ks.yaml
  # - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  # - ./readarr/ks.yaml
  # - ./recyclarr/ks.yaml
  # - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  # - ./tdarr/ks.yaml
