apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:7fsjpuID+v9Ni6GvORNxNJUD/cFyEXjbxmV6HnttxKk/hp4lD4iqkQ==,iv:Jh7mxJXvBHq+FmHA1in6950AW9mIgXwh/DFDizGB7AY=,tag:kB+a/7n1REX0/w5KxWi3rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZkQrUHVHcGNzTjhlWlRl
            RVFEZHpDMEJlc3hjc0dpSHNKRHk4aHhab1VJCmdoQ1puTXRJcjN1ekNpM2JLR3Jr
            c1BtdjNZekFaWEh6dTlJR1dIMExuaE0KLS0tIC9kUHRpOExXZHJCQWNtTXYyZnoy
            YS9LTnJMTTFveTJ5M05jNlZEMFA2N1kK9jVhpMG0IKyYRWMx7+Iqb+CjSwWm6IMp
            2GHZmv+2zSa0cD2+8Kij78W0hVusendqmcjcWy87qxba3ng813aLNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T16:30:11Z"
    mac: ENC[AES256_GCM,data:R2J8OE8T6BngfFbnXHKXT+qGFMBuiqLl6/mzSK8gyvLv5XL+6z196zhXuVTZcuogndxAqx//a1sbCQ87g5/2z7npoQQM2lyDpI/QNWEw8DkLQjjDh+OKaiSmhRrV62mmuEsN8CG2gbqpVo+RmZ9pRdh51mnLvJYr/ExSYr8wrTI=,iv:6AcqLZFnxBm+8W9Ly6vQpikhocckU2QJzOYv3TkX6Js=,tag:Txv6JPQEyA1BHyqLeYXwZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
