apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:1umJlwJhn3Z6MB/0pACofbfMTlet0eXIEjS2rGcqF+ARI+A7mj/cqw==,iv:jrEBn0R9etZYcwutJFOqmtYaTGJr4pjksuFJMJAGUdE=,tag:3+iLs8jV8AcfPq9mwHPT8g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEK1dpc3JabmlnL25YYXZ1
            bVRSQjY4azhqaWh4MjR0bWJjUEZKOENrN2xjCm5JUCtGeTNNNjZ3cS82N0pUUm45
            UU9QbkRYVHJOdWJXM0dQUW84VHNwKzgKLS0tIE9pQUZtSzN6SnhCVkpCbEJDSkhD
            azB6a0t0aUQySTlnZzdYVno0Tk9heFUK4+DXXs94a80qODE94XMf/mL3Bw+GYfs5
            E5yqMk/a8FNHUJqYb4XNos72HbOl94Tawi6pSKcayScXQknaXiJduQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T17:46:41Z"
    mac: ENC[AES256_GCM,data:Jk6yG9j2Pa2SU+AqE0EIK02OhfSMcDgiQPVnQjdrR1rn/vvOiuAr2O93GVGzRAHqgHAzws2tkVsolPc46KLcPNZ81dx1m4/H8TmrmsaTOCvArEFFwGwi84QQHYisL9IYZitQIfnORwjEW9+LCNytWpNUiQASD5Taqed6BFYZdy8=,iv:3iLlN3W0H9SIrZQ9Fju6eMKFtp9J1YvXkdLuzyiIrT4=,tag:3C2x4x8K+QznzoaK/5xk0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
