---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: plex.png
    gethomepage.dev/name: Plex
    gethomepage.dev/group: Media
    gethomepage.dev/description: Plex Media Server
    gethomepage.dev/widget.type: plex
    gethomepage.dev/widget.url: http://${SECRET_UNRAID_IP}:32400
    gethomepage.dev/widget.key: ${HOMEPAGE_PLEX_KEY}
spec:
  ingressClassName: internal
  rules:
    - host: &host "plex.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex
subsets:
  - addresses:
      - ip: "${SECRET_UNRAID_IP}"
    ports:
      - name: http
        port: 32400
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  ports:
    - name: http
      port: 32400
  type: ClusterIP
