---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-web
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: calibre-web.png
    gethomepage.dev/name: Calibre Web
    gethomepage.dev/group: Media Organization
    gethomepage.dev/description: Calibre Web E-Book Management
    gethomepage.dev/widget.type: calibreweb
    gethomepage.dev/widget.url: http://${SECRET_UNRAID_IP}:8073
    gethomepage.dev/widget.username: ${HOMEPAGE_CALIBREWEB_USERNAME}
    gethomepage.dev/widget.password: '${HOMEPAGE_CALIBREWEB_PASSWORD}'
spec:
  ingressClassName: internal
  rules:
    - host: &host "calibre-web.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calibre-web
                port:
                  number: 8073
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: calibre-web
subsets:
  - addresses:
      - ip: "${SECRET_UNRAID_IP}"
    ports:
      - name: http
        port: 8073
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: calibre-web
spec:
  ports:
    - name: http
      port: 8073
  type: ClusterIP
