---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kvm2
  annotations:
    # nginx.ingress.kubernetes.io/enable-cors: "true"
    # nginx.ingress.kubernetes.io/cors-allow-origin: "https://kvm2.${SECRET_DOMAIN}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: tinypilot.png
    gethomepage.dev/name: TinyPilot
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/description: TinyPilot KVM-over-IP
spec:
  ingressClassName: internal
  rules:
    - host: &host "kvm2.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kvm2
                port:
                  number: 80
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kvm2
subsets:
  - addresses:
      - ip: "${SECRET_KVM2_IP}"
    ports:
      - name: http
        port: 80
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kvm2
spec:
  ports:
    - name: http
      port: 80
  type: ClusterIP
