---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: 'off'
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: nextcloud.png
    gethomepage.dev/name: NextCloud
    gethomepage.dev/group: Office
    gethomepage.dev/description: Personal Cloud
    gethomepage.dev/widget.type: nextcloud
    gethomepage.dev/widget.key: ${HOMEPAGE_NEXTCLOUD_KEY}
    gethomepage.dev/widget.url: https://cloud.${SECRET_DOMAIN}
spec:
  ingressClassName: external
  rules:
    - host: &host "cloud.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloud
                port:
                  number: 4443
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: cloud
subsets:
  - addresses:
      - ip: "${SECRET_UNRAID_IP}"
    ports:
      - name: https
        port: 4443
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: cloud
spec:
  ports:
    - name: https
      port: 4443
  type: ClusterIP
