---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: switch
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/icon: cisco.png
    gethomepage.dev/name: Cisco POE Switch
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/description: Cisco POE Switch
spec:
  ingressClassName: internal
  rules:
    - host: &host "switch.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: switch
                port:
                  number: 80
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: switch
subsets:
  - addresses:
      - ip: "${SECRET_SWITCH_IP}"
    ports:
      - name: http
        port: 80
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: switch
spec:
  ports:
    - name: http
      port: 80
  type: ClusterIP
