---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: default
spec:
  ingressClassName: internal
  rules:
    - host: &host minio.${SECRET_DOMAIN}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: minio
                port:
                  number: 9768
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio
  namespace: default
subsets:
  - addresses:
      - ip: ${SECRET_UNRAID_IP}
    ports:
      - name: http
        port: 9768
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  ports:
    - name: http
      port: 9768
  type: ClusterIP
