---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ap1-ingress.yaml
  - ./hass-ingress.yaml
  - ./router-ingress.yaml
