---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ingress-external-hass.yaml
  - ./ingress-internal-ssl-ap1.yaml
  - ./ingress-internal-ssl-router.yaml
  - ./ingress-internal-switch.yaml
