apiVersion: v1
kind: Secret
metadata:
    name: hass_ip
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTV1ZvMUloZ2t1dnRyMnVD
            UytvRmVBMC83RWdDN0pnb2dOc2FSUjhHN1ZnCmNPSnpCM09IMytGTVBFWVhtRW1Y
            QURWQmsyUnNmbzk3WDZ6VktzaVJySmMKLS0tIGJCd29ybTVkMXNqRGhtVDJMNFBY
            b3kwQWZhbmFOYTJ3SVlOUzNzSWFVT0kK9gIu3EjKU+mY1DZqvCBOcxCWg4j+/mTo
            PgiKBA8GVBKNuQxbbYCTUYc+rGz6Dwvs/tcsj0jkXd1Vas/EmADN8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T23:13:20Z"
    mac: ENC[AES256_GCM,data:sQoaGDdcUHkyFMquQueyNud4+EmJm1USgv/INwtX4MUc7hW83QR89g4Xd6waUlBeS4dyl8og1XE9yAmjzjSPNlPgeyxdNwMxuRGboYnegn2waLllLPWGR05ZB1yPwhgHq2TfkIqGOJco8iMFwLZTixw2QDPsMJ4GhXmoDweconI=,iv:QRXLNyZD0ZGYaPH0E5AtI6sh8qjGn6ejXl5Oy3WsJfg=,tag:MRPCCngoIKYPRQh7piu+5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
