---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default-mealie
  namespace: flux-system
spec:
  # targetNamespace: default
  # commonMetadata:
  #   labels:
  #     app.kubernetes.io/name: *app
  # dependsOn:
  #   - name: external-secrets-bitwarden-secrets-manager
  dependsOn:
    - name: longhorn-storage
  path: ./kubernetes/apps/default/mealie/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  # wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # postBuild:
  #   substitute:
  #     APP: *app
