---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  dependsOn:
    - name: ingress-nginx-internal
  path: ./kubernetes/apps/storage/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: longhorn
      namespace: storage
  interval: 30m
  retryInterval: 1m
  timeout: 3m

