apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:r6lugmXiVMDZ7TxQtnGAWNsC29uCvzvpAVsrXpKLoM+pgCZrQEh7DNHGyip20JnH3y6e2Wvo8rpj96CgK4elcqEIhMdFsagvK95rtVbonVijs6VOj+VASRwLW8Tw6g==,iv:BAOGYUSPrSg2G4c/0ThTKFxjbvruGrqmhKAl12SDzl0=,tag:bc4J2/HEYhZvwFRPSpmI4g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:oLp7GJ1W41GG,iv:DwS20OxEBOqGDtD4IIC7UFk9ORDIRZ5FhCzMCmG7hIc=,tag:paj/THQOamc6QP5hERpL8w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:XssGW3wz+d9Ti2lM+8h97aLlDJwnLA==,iv:UbPFrgEwxfCo1kod5f9BjmInm9tCHZHA8E1E0q6mD2Q=,tag:ozOsR9zX/PIHeuS1c4ThEQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:S2xSgmwX7ekjTlmX3dwZIPyh4ScIR2ujxPawg+Z/Wa6XVGrw,iv:JcnljOOy/Mk7lnR7GBMwG9jzdv77YyQCRxyhBhUgdb0=,tag:Q6uLOOsJ4hsYAMrfbB+IKw==,type:str]
    HASS_IP: ENC[AES256_GCM,data:cSg+dn9+mSU=,iv:K0ODemqzWOYDLgHpEM1QRK1Duxp6Su42yYB08Z2FbFE=,tag:3mZF+TSuV+m9Um0xHkHdzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN0h5bGxsRktDN0REcHlF
            aGJVUFd0YnJ3ZVBwZHFYc3BRbDUwY3praldNClR3OUIzc1YvSEpheEN3RTdzdGF3
            NzI5OWNGL1lBUys2TkNtRS9XKzlGL1EKLS0tIGVER0FPQlNhQmgwazNwb01QZ3Mv
            TFNTSVowd2l4VzZGT3BRUFJwV0JvVVEK3dzjVf2w6MQyb4LKHvv5reALFB0sz+i8
            TEG71xT9pB8h/FfcQWKgUkbZJDy9n3mQmgJ5I9+Tty013Cd0vFDqsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T15:48:44Z"
    mac: ENC[AES256_GCM,data:S/cUy7R1tHEOjofymeT2Ag/PteD795U+OmjgsfiLowe4umYxPuS2MutnjwUdYsoDMPE7ZWFRm/SJSZHvKknWSZAwdXCa8Pg8B4aS9AGAO/5lBYdxAM9GLnAAfjCpnQP8RpPq3v3xio1uWySrWgra8jo1rqtbxd1Ipvrw5e8OHPs=,iv:SLlD5BWgok6s6NX/h9ubHUiJsrYX7hqOEcNHJp1g92s=,tag:wvU3zWaYQfyAuGbTc91+6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
