apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:BL8hM4ZNVvGGzkzFowYAICczPCSETBVDWkiIA8Hl9ubtGrzw99z+mZSusyFrUcGB7N5z63CLuiXXaPWdIIeuP9M2sQ5IeQg4IzDVHyn2cvkfxvwtfwJLaebj+YvrJA==,iv:6cJmffi0lWEZGzL4CQ6df8/oqeqryAtcMzEZLr/bCrM=,tag:WEVJ2b17jyVRvbewnGz+7A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:dFZdDucSWVtT,iv:JJYy44k2lGUm/nwEkuMHd9nKNg0cJURQtikj5+P3WE8=,tag:rweyHYOy/xgi+aOdU2IWpA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:jPF/kutg51P1rf3Mca7nX1Kuz8R4tg==,iv:Vph1Veg4JAU7qYSEmotH2IBWCljVL7rFD6TmAVKVBns=,tag:TgLCqIPGGEgABwgM0UQ8Vw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:SwJ65oR+MkR9rrkAV5v/0t2iOpAKY2cfDkAZaE4Twbuhs7QO,iv:3UC73MVyBBg+CH14FFeSidRboxrwBTAecgRIBIWPAyE=,tag:ofpvaQUFid+JdUpmM4IOXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbVE0K1M4WCswRFdCbEV2
            Zk11YlpTbUREem4zV0lud0dUMDRQWEozcmhBCkNXbFBxN3RKSUJGTVV1M1krSDdY
            OFJBazkyMFRuU3RxQndWaTBIZEk1d2sKLS0tIFRyeWhMWm1PK0pPQTJhMWE0Rjc5
            cWN1MXF5M1VSQjBTUVhWYmJDRlBvTjgKzdQmNbkSZUQFkKIG367ZrTGDT2v5OX5g
            CAy68d0apCVw7g+qKUedBdq7iGU6GPUgAk+Br6AxMksSEKWfbmpH+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-15T23:14:03Z"
    mac: ENC[AES256_GCM,data:dpafd+FYV/LJYRycSrKCKrsFOn7F4uKRCacSRRZPv2F7FUUSTlZsgx+SXAiNzsqqvhH6qI9/JQKmhyHHB7cmXP0S0+m/NBOAV0xgG1/sjNFkhzeuke7Ma3nvUuNgarw6JcPOavGhaI5lKDdlDjJ2TK5++J39R6josI4J5HaboCM=,iv:MowSK9l3q2pCp7+bwxBP6+GvBvbmWBdzuX99JQ5zjrE=,tag:jY8UxL0l4RFd0RpMPc7E5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
