apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:CMuzYtbMSTOyUWgsk3rJYgOev/aiEZOW+dJSRiu1JqZSbvg9gDcJhNJwvXW8z9hsKEjfnXRw6xqIURVdwQoxcYxz1K4z/MGKwW+s5/EF0e3MntCU2z8jzl5QuwWhlQ==,iv:Lsmv2qh40gUC7nSH0yzfHvijU9fYd1baGaBrMqhTIp0=,tag:Tp73OMnkIJ+W2m5P8l8DBw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:o4Fp2DZyfpUD,iv:fpT8raWfl01Cin/T4sw07l9AQx2l++/1T1IUFQZyRYw=,tag:3WtefGmQYPPCe9Qd5o9c8g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:WRNhebU6cR/CM+h9XkVAs38ILykCoQ==,iv:1kDpyQB4Gth4EKjMYJraiIkCTfABJok8shYPAltmb2Q=,tag:OroCEl50pte3dyfq4F04sA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdlJXSk9vUEd4UDUyL1NI
            akhRWlZ3ZlpxY2xKV3RvdlZWUGQrUWxLelIwCnFNbDhJenlRN3Y4NEVVWU9iZVVu
            THBjOGhoQ1RqbTFqeEI4cGZlZGtMcUkKLS0tIHdmbGVSY2hBZDN6K2NqRmxkZGt2
            eDg1ZXphY3FmSGhoSkU2VkxlVVA5RjgKe31RskhWfr1rLWuMT8/srNPH50cWMQjU
            LtwSohyC/b0lRO0itH/9sApnwtw4AhwNoc48pYRZao54Aj3m32iAbQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T16:44:26Z"
    mac: ENC[AES256_GCM,data:Gm4kjQgx84Owqhf/WQP6vIznegEyU5hPLzIYeThtzZ2K5xiLJkOeMm43sxpInhA32wJWZsqe/JPZrrQn9MgIpxnd4uIg4pO2M2cUww6A0eevA8HRtiifvjR0Y7znftOCLRjFHZW70j0DMP2p6Oi01CYQGhXzv1BKU8G2nch+uOI=,iv:3uIAcEPtw3Rr3TWOjD2UbUSYIrRqlnHqVDHFZTs6hv0=,tag:oHksBR5mJvq/hL4duC/w2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
