apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:RfHVkegVcpBaq+eYOi0H3dhYilrybjCWWm5/aPlfoGbYxStl4moGROCQila0YDhRQjeSJxAGca9JrS/yMHWGHJJyzuRpwxmVQNrziutlsQM80gNwpxr0SRArHARmtA==,iv:ums5NPLmS2vWHYB/t8klo60Llmva1PzENnku4iVKQHo=,tag:OD+KQznQCLnQisyQNh/64A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:o+uIp0RIU23e,iv:C4YE20SYLbEyessK/eeEir+mVPkf3jDMiMfipW9qLKc=,tag:zcnqqoda0/JiGXBQHifRpw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OGpjNDW+0HsXJT7BMGiBK6LiqpKLvQ==,iv:LbMY6NeArIXdnZS7t/iDcEFn2uzPwzCfXr2xqEtqY5w=,tag:1ynEvI4U5RZINjgPBM6MpA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaGgzeVZRUndKY043Lzdw
            M1FyWUEvdEY5ZUhybFdYR3I3NXRYVjlZcmxrCmZHUHU3SjZNR3pZSE9RVTFsZHVQ
            czd3Z0NKY2JXSGVBUktHa01wV1NoK00KLS0tIEVYUjlLWTRPVURjbG0yNFR5dUV0
            Y1pyTk9rR1ErUUNFejdKODdwWU5adncKgIYv14O3oj8Wj346biC/yCYD1KNCRmXJ
            H2y7kzgCQNRZq1r0nv89Mco/zTO4beKhJtBjCimYNb7Yj3krmcjpzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T16:30:11Z"
    mac: ENC[AES256_GCM,data:r7T8XgjJGxOryn0X9z+p83C+5l+WaI5qrqAA32BzYo5hfXRY3PLUz/xyLXvSmNCsdbAn5PfjmgAHv6emnyTcaYbv1iNDjFOdLvvQ40xd6BK2iWr9g1T+XGJjHfc+9fj1Ub+7wyBMvtl/OeCRNemCF8a4QMoLxanaJaYht82xYas=,iv:LRs9Gn2IJSArvbFf7Zhg+lCY3UmZTOmMjNt0m1y4IeQ=,tag:HWczXK6uuoe9uoMbez0yjg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
