apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:jONA38cm/j0cgfAJLSjnqgMtdnEFGmP+o7ezsjHdwN2h3AFn44oJYXe2yFflzBbtcGbcDROxaZGUA+EFiGhwvn5U+w6pu7hQjdUQhD4KaPVysCyWd8OxeR9Ko7PaPg==,iv:kM671YGtqlCItl/PMnWC5nUNCtZJ+YsLpSbdAeZL1Ho=,tag:Qvnm+W3f3cpPeYjdjTS64Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:1kTw9bciq06b,iv:Dgs61HrHy3rl3V0f8fO+bmVvC42ziZeyIIecslL3akY=,tag:cJalKaFw8Z1lKcz2MNTSVg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:79nmWkq2syL+ix1dcQ7Nr24JAw30zA==,iv:rO0TCJVK0kbPBZtDOUqZPp8hZo57zNvIHHh2psJM8Vw=,tag:F7VEyYYSXux/oKtb3wqi2Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:5EPMdWQ3s4jzRl17v3Wzz++wdoIO1Izys6XRgj5Ii/qREyfi,iv:3PKljC9dT74+zEy7BbHJjprv9NMzgW2KY3jCVJ6ZOn8=,tag:5L9plPArgzZEwLG34vbmdw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocnQzVkJ6a1RCcytVejgz
            RVluclQ1QllNK3dobHhBUkVPV0U4NkprN1U4Ck9xcmRIK1Q0cmdnK0NGQ3ZkeUQ4
            TGtUMEFZNHk0MTVLK1N0c0tlU05xU3MKLS0tIGZQZDBsdkRpcmhxZ0g4V2ducEhm
            YUhxTFY2clc3cjBCa1VRODlwenR4V1EKNmmP4NpmAq6KNzrh2QjtTUhoWZsU70EG
            quxEVaFRK/Qb2id4+tUtgQOw5/s2ezcJUd+rer85kvKRJtHJ2EXQFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T11:53:48Z"
    mac: ENC[AES256_GCM,data:BfhU3A71dhtJcQJBVi3ovNfaEfa9bNxV8JvO3XdOucYuCK+q/OF70Wwruy9StXDNk56UvonVwTJjEezLozz2sCJwa31E0ALEH04AWYfuKW/BXdn0MFXDWdbpd1mc2FHFbxMdlTE24QpWMgxzvMx7UK1d3A7eb6fxreehNYrEIAo=,iv:v9zVs8J4jM+owsKx11HLTj5c/gF/RrXXRdbOIQ+Xxfg=,tag:C6wUj1A16478SMnw+jKNxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
