apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:soeu7ht7PUpu3JYgmXVUZLepZb2L8AJhiynzd7VQk9pUd+8qf362+tyeep6wmkw48kby6Bq6z+VpjW++PAcJhlHfz6W/vOWyGXuP+7kTGO8as+yo/m9Ju61lB4xKvw==,iv:FKyymvVltzGu2wIxyY2TRPwMLvH42aC9xoorteueiic=,tag:yMbfH3OMp/eNKufvdK3tog==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Y/EgFLPiyGy/,iv:LQVL2APPM6DfP2/2nCvRyCK1S1HgammM96/sRG3vJ0E=,tag:YqKxgmSUr75rwx3WzMdNyg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GAflsNwr+h+795eNS86/RfdsaucqAg==,iv:4WZfV0IfsTRkCCAcmxZni4gi9PYZ/aXYAcmMdhXCIPw=,tag:jHBAWeXFmbOTGtCi911Ylw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:CyHTfF5KwOnYGU4kR8Kpa9wb1fKV7Vc4Od4xMzCv7jjB6oub,iv:vnXMCF3E1UsobdLcLHbvKZhd5Xr7VcU3blpz5JfFkXE=,tag:k2/l9jpd09+01WGlTl5roA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ0RqdllEWUs4MDVsZGVC
            SnE0QzRoRExzTXQ1VkJsMVVsSDNEOStkWFVBCjdsMUwwOHVCVTR6V3Z2M0l6alhr
            bnROa08xdWtTRHRsNVhjQTdaQWFsSTAKLS0tIFJxSUI1OWR6ZnB1UjFEUmJtVm80
            Ti9mVEFaN1VwMFBNQjU2dFBza0dSS0EKCtSZHPuEgqslRIT2k8MExmkUBwtVQP1Z
            i6ZeGOi0JwwcsZ/N7SPp+SlIwERLH+r5YmZdAmDaBjp0KxQYFzgjDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-16T12:48:39Z"
    mac: ENC[AES256_GCM,data:EcC5vkZSNZo7SzsfD9V/hGS/aMqNPgji5rU5kZLXC675zWCCNMhP6fZe6XAadLR+sj3gOqPyUXm7AHVsm+CT7wRqEY+Z7LrD9QGfVyA9MMZm76FP+SVP+AgvHQdwDNSya+3MjeAOaJAncfRNf0DQRaGfcXs97+sKDkOg3mX5v7c=,iv:exaaWRmPYM3/qxYvgzBbKey1SfHZxuNHP2Ok4TMQ3QQ=,tag:8BrRB6mGoi7a1JbBZ4zyKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
