---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.5.3
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    env:
      TZ: "${TIMEZONE}"
    persistence:
      defaultClass: false
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain

    defaultSettings:
      defaultReplicaCount: 2
      replicaAutoBalance: best-effort
      defaultDataLocality: best-effort
      backupTarget: "nfs://${SECRET_UNRAID_IP}:${SECRET_UNRAID_SHARE}/backup"
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: 10
      # defaultDataPath: "/nfs/longhorn"

    longhornManager:
      securityContext:
        privileged: true

    # ingress:
    #   enabled: true
    #   ingressClassName: internal
    #   host: "longhorn.${SECRET_DOMAIN}"
    #   tls: true
    #   tlsSecret: "${SECRET_DOMAIN/./-}-tls"
      # annotations:
      #   hajimari.io/enable: "true"
      #   hajimari.io/icon: cow
      #   hajimari.io/group: storage
      #   hajimari.io/appName: longhorn
      #   hajimari.io/instance: "admin"

    ingress:
      enabled: true
      ingressClassName: internal
      host: longhorn.${SECRET_DOMAIN}
      tls: true
