apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:XeJv2BzXWg7jUsNyyNt6orowlJ+mFHYUsjrY6jAUxT0=,iv:jig4FWygz+g2sfkapdf4/I2WlwaojYch0c7WPPB0pCA=,tag:axC+wbf2yppLx2+eGiDGbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNjdLOEFpSmZhSERlWVVr
            VjIvenREM0ZWUUJsbm1CckJzZ1lKSHN1a2cwCjc1RTl3WlBEZHJ4eXQ5T3l4MmIy
            UzVDeW5IYzZKOVBKaHMyR1hwOEo1aE0KLS0tIExBL3FyRmpDTTBrS292R2ROU2Q3
            eWpuV0lCTjRROUtWQ1Z1K2k4R29YN3MK6JXfWF9EoRaWWade2arIlw7x4Xni/FxL
            ZbVHJ2VekuUbApnFWbJxzr9R4PyzIgHiaHJzOi5GQMUjhGIlSMUwFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T14:56:07Z"
    mac: ENC[AES256_GCM,data:IT5VJUYNBceTvwIRLezZG/JHEDqFiu353UWBLTTKd94glbhRAidgx56rDs8edNRtgGvFKZwYr20fYDiIhqxiu6fdxze7lBOs3iBfWCeExA8rHDPtzyh+rOKGWFLJ7D/22F+lBy8qVvNihGJERkIu3zxCezH8s4898ir516Sr1lY=,iv:/9Dktu8mx2P55E8srhwGLh43YcjoniJOhlRo7JMOUgQ=,tag:BTUxrD2HFcnF7HzvnRqpTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
