apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:YyzMw4UxIiXmM2fSvV5LsWqo+VrOhbn6xDs49Fetev8=,iv:JHIQCwefTdGGNZYFDjc85taQ+qxa3JHVtQW+CxssqQQ=,tag:C3Z6fMoWLlRfy1NNBiVuuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcHpoZC9reWNtWDF1RTVy
            RUtQL0RmcnMyenlyVFc2NmI3VWZvQ3VpdlJVCjNxRGVQZ3RwSkxPditvbE5zRDFQ
            UTN6RzI4YkIvNmNxNCtlYnA0UXgycGcKLS0tIFpzTjZTSC9Zc2orZXNocUVWYXAv
            eERrVlp2RC9SeDFMQlYwWGw0czhaMFUKEtlWN3Isg/KMSjCbysf6PF3RMZ0zkHuW
            ywfyK6DdgMkAUYwvdn4ufLQnzDaY5aUzNgj99q80jpnuCpNEvHjCow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T17:38:12Z"
    mac: ENC[AES256_GCM,data:ygSzIw3zjAgc1E7C4cJmVBkbrAW4eJGweaAoLjY4EyVo34SLxv02NanPcsjN2Dravq5cbMKw/bnCq48P+t5n85qn5/YE8BkedotnimKKt1h+W/xw4GIWglXWJGXUVLisamMVW033yfRdQLmQAR009BxRSMlbbmfYGJuKSENhwpE=,iv:XYHBJ6xzHOw9rIyybvt5eLRpQsjkTzxImGJ47T3/+rE=,tag:StEs/tQ9vtD2GvysqBKyrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
