apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:BFpkWFtQIFIxMC4WrijqSo3roYQtL8bKoO8gu60f0cc=,iv:nRovi5SatjSHUQI415eTi0ORidyuUNZ3N2EAir8q0+4=,tag:OJbYYRC6Fls+QP0pZD8pbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqN3RGSlhyc3VSSzY2Ly8y
            MWVpQlVibDB1NlEybWNqcVNxRTlYSFRjOERBCklBL214dDVNdTErL1huK2tGbFlp
            RGpTaFZlcVc0bXBhQlFGU2Z4K3gzdU0KLS0tIEg0MU01ak10VXZERGU5ZnVRUFJ6
            aUpVVkkvUCtzV0c0aW1PTUNpZ0ttSE0KVDUaP9xHtpRgRRdetKiMBPT4cxNjQGG0
            gUpSrQyO9HRWK98kkrbGC6ULiL7PdCYIFBoezz5RMjhkHl/X4NoDyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-05T16:30:11Z"
    mac: ENC[AES256_GCM,data:iMEZWVp5LywW39+UOES0qcyidnkvetvLUVipF3qnnrCEQZoQQ3B0mZASjOisxSnHD/GbAVzSag1HyqscjG+dNcT5JpcxrPN6Km98RRPhH6Tf0oLfLOtmV1PQ7Sir7uD5iXB9npeGWl2THnzjOWEMvD8oAcBEddYSvY7z9ys9JnY=,iv:VPrp7PzFzPdbDLISE1dL6RhuPNejD1foZqBfirQEvfA=,tag:EIJd5AzYaWmFKRb4igcgnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
