apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:BJxSpbKx9KcD1EvbPU7dT/vZ7NbHPnmTnHw4v0DP1WKiY8HQvqZAtg==,iv:eUoYa+UgII0Q5zKxQMxZQWrWzekVSD2GPNQg5dCxww0=,tag:CvY4kwf+ubq47kUjI9dyOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbXRYY3JGd0JScFgvWkNJ
            N2VTdUtDb0FsdWQ0dGFHSEpVOWtwemdJd0Z3CnY5b0pHVEM4djV6SjQ3YXVEMytO
            Z1NCMUlFanRSOXdUV3JnT3p3bXU2VEkKLS0tIGFZaWoyUUV2RjVHSW1oVUd2a1Fi
            MUhheWFzZTRVQTU2WTBtQVBiOUxlWG8KMJDWwMR39n3vVnAGWLL+L4D/LqgvMBVE
            VzaTxiXehQKdIlOsvHhL8p8+U8sHdlKqFL0CvaGqYCSUo5qd4Uk6sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T14:56:07Z"
    mac: ENC[AES256_GCM,data:l7gHJqQ7ebP2UPkBbA7sskfhxIoHHLqTZMWSYPyakrmJkGF8YHLkD9XX295Zbp6QrGT/98+HvuDxPWhmBUOZ+fQX7cpns40ON98iltxjC8Q8JVxtPT9Sx09BESXzvLJCwNPFjBEiR2LRryv5DVlUc2zM2041NCDglImbbypubB0=,iv:pL9IMBqRHx8IMNUiKgr/j1EMTgpe9bXDJpGEAbXfI4w=,tag:hMzTWaYmVEK5NyMlwzTNOA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
