apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:SXIOQwZO+WMPEiheUXBK+jDXf19cs7ECVg+zN2ZQvJyIauVC0wk3vA==,iv:a7sfMJlSKU0QRqln8GS9GdlQa0cUg9gG8qEtRWNJo08=,tag:qU1Guh7fKzvTTGpme7aYsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age133h2cxn3jawucfzlcrvme4p62css8ceqevdpa0g68nyccrqg4yxq202ytw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZmNYaWFJVHpXU1hoSmFs
            dmRTODJwNGFhUkdFSkNKNUZEei9NdnBqVUFvCnBwaWdRclJnekMwUGkwb2FmZlV2
            R0YyWkIrOVduandIOVZsWTFHeTFYdWcKLS0tIGsvWWZ1T1lHekF3UmxUdi9Lall6
            ZEo0NHI3Ky9BRUoxTGVnRWRLOVI2U1EKHP/3Wa+JKrGef/HJkZJXEsThqUZ+7hVV
            bIn/dr+y6PWCDC6UYh7OGQDkaJ625RFDCzoYfumAH6f02DT7hYAkZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-06T11:53:48Z"
    mac: ENC[AES256_GCM,data:zPZCHwyfki+4V7XDOebwNK6JoFQ/7epVnrUMgGaqg2sr9NiZ2Gu+5CabKYOnOPdPj8Lp1acK8mIwM3LidE21Ha3EzvSYX/cCLs25vlHhXW8QeDYoUaz9HtAxpTDVUZnainiZJKSN+DUAhqXOQYmKefDb3lf3O4RPSIKfHVrH6Uc=,iv:j5lhHN9hrb3q5Fwlv3PMuSTDHdyV6mXFnK7JnfqLeCw=,tag:fNWnsIJA3IENX44Lv4pdmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
